version: 2
executorType: docker
containerInfo:
  - image: circleci/build-image:ubuntu-14.04-XXL-887-0e8804f

stages:
  build:
    workDir: /home/ubuntu/mruby-cli
    steps:
      - type: checkout
      - type: shell
        name: Install System Dependencies
        command: apt-get update -qq
      - type: shell
        name: Install docker-compose
        command: sh -c "curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose" && chmod +x /usr/local/bin/docker-compose
      - type: shell
        name: Run Tests
        command: docker-compose run test
