version: 2
executorType: docker
containerInfo:
  - image: circleci/build-image:ubuntu-14.04-XXL-887-0e8804f

stages:
  build:
    workDir: /home/ubuntu/mruby-cli
    steps:
      - type: checkout
      - type: shell
        name: Install System Dependencies
        command: apt-get update -qq
      - type: shell
        name: Install docker...engine
        command:  |
          curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker.tgz
          mv /tmp/docker/docker* /usr/bin/
          curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
          chmod +x  /usr/bin/docker-compose
      - type: setup-docker-engine
      - type: shell
        name: Run Tests
        command: docker-compose run test
