compile: &defaults
  build: .
  volumes:
    - /home/ubuntu/mruby-cli:/home/mruby/code:rw
  command: pwd
test:
  <<: *defaults
  command: ls
bintest:
  <<: *defaults
  command: rake test:bintest
mtest:
  <<: *defaults
  command: rake test:mtest
clean:
  <<: *defaults
  command: rake clean
shell:
  <<: *defaults
  command: bash
release:
  <<: *defaults
  command: rake release
package:
  <<: *defaults
  command: rake package
